version: '3.8'

services:

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db:${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./${SRC_DATA_DIR}/wordpress:/var/www/html
    ports:
      - ${WORDPRESS_LOCALHOST_PORT}:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/wp-login.php"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - wordpress_network

  db:
    image: mysql:5.7
    container_name: mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./${SRC_DATA_DIR}/database:/var/lib/mysql
    ports:
      - ${MYSQL_LOCALHOST_PORT}:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wordpress_network

  wpcli:
    image: wordpress:cli
    container_name: wpcli
    env_file: .env
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - ./${SRC_DATA_DIR}/wordpress:/var/www/html
      - ./scripts/site-config.sh:/var/www/html/site-config.sh
    command: /bin/sh ./site-config.sh
    environment:
      WORDPRESS_DB_HOST: db:${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      HTTP_HOST: wordpress:${WORDPRESS_LOCALHOST_PORT:-80}
      WAIT_HOSTS: db:${MYSQL_LOCALHOST_PORT:-3306},wordpress:${WORDPRESS_LOCALHOST_PORT:-80}
      WAIT_BEFORE_HOSTS: 30
      WAIT_AFTER_HOSTS: 15
      WAIT_HOSTS_TIMEOUT: 30
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30
    networks:
      - wordpress_network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PHPMYADMIN_LOCALHOST_PORT}:80
    env_file: .env
    environment:
      PMA_HOST: db:${MYSQL_LOCALHOST_PORT:-3306}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wordpress_network

networks:
  wordpress_network:
    name: wordpress_network